# What do want?
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pvc
spec:
  storageClassName: cloud-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 31Gi
---
  # How do we want it implemented
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cloud-ssd
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
spec:
  storageClassName: cloud-ssd-2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 31Gi
---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cloud-ssd-2
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 31Gi

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cloud-ssd-3
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2