apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: orirothschild/jenkins
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: jenkins-persistent-storage
            mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-persistent-storage
              # pointer to the configuration of HOW we want the mount to be implemented
              # i will have what he is having kind
          persistentVolumeClaim:
            claimName: jenkins-pvc