apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8081'
spec:
  selector: 
    app: nexus-server
  type: LoadBalancer  
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: http2
      protocol: TCP
      port: 5000
      targetPort: 5000
