apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
        app: nexus-server
  template:
    metadata:
      labels:
        app: nexus-server
    spec:
      #i will add this to be able to create repositories inside the voulume claim
      securityContext:
        fsGroup: 2000 
      containers:
        - name: nexus
          image: sonatype/nexus3:latest
          resources:
            limits:
              memory: "4Gi"
              cpu: "1000m"
            requests:
              memory: "2Gi"
              cpu: "500m"
          ports:
          - containerPort: 8081
          - containerPort: 5000
          volumeMounts:
            - name: nexus-persistent-storage
              mountPath: /nexus-data
      volumes:
        - name: nexus-persistent-storage
              # pointer to the configuration of HOW we want the mount to be implemented
          persistentVolumeClaim:
            claimName: nexus-pvc